apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-serviceaccount
  namespace: crossplane-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-serviceaccount-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: admin-serviceaccount
    namespace: crossplane-system
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-serviceaccount-token
  annotations:
    kubernetes.io/service-account.name: admin-serviceaccount
type: kubernetes.io/service-account-token
