//go:build !ignore_autogenerated

/*
Copyright 2020 The Crossplane Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityInput) DeepCopyInto(out *EntityInput) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityInput.
func (in *EntityInput) DeepCopy() *EntityInput {
	if in == nil {
		return nil
	}
	out := new(EntityInput)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityWorkflow) DeepCopyInto(out *EntityWorkflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityWorkflow.
func (in *EntityWorkflow) DeepCopy() *EntityWorkflow {
	if in == nil {
		return nil
	}
	out := new(EntityWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EntityWorkflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityWorkflowList) DeepCopyInto(out *EntityWorkflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EntityWorkflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityWorkflowList.
func (in *EntityWorkflowList) DeepCopy() *EntityWorkflowList {
	if in == nil {
		return nil
	}
	out := new(EntityWorkflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EntityWorkflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityWorkflowObservation) DeepCopyInto(out *EntityWorkflowObservation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityWorkflowObservation.
func (in *EntityWorkflowObservation) DeepCopy() *EntityWorkflowObservation {
	if in == nil {
		return nil
	}
	out := new(EntityWorkflowObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityWorkflowParameters) DeepCopyInto(out *EntityWorkflowParameters) {
	*out = *in
	out.EntityInput = in.EntityInput
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityWorkflowParameters.
func (in *EntityWorkflowParameters) DeepCopy() *EntityWorkflowParameters {
	if in == nil {
		return nil
	}
	out := new(EntityWorkflowParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityWorkflowSpec) DeepCopyInto(out *EntityWorkflowSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	out.ForProvider = in.ForProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityWorkflowSpec.
func (in *EntityWorkflowSpec) DeepCopy() *EntityWorkflowSpec {
	if in == nil {
		return nil
	}
	out := new(EntityWorkflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntityWorkflowStatus) DeepCopyInto(out *EntityWorkflowStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	out.AtProvider = in.AtProvider
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntityWorkflowStatus.
func (in *EntityWorkflowStatus) DeepCopy() *EntityWorkflowStatus {
	if in == nil {
		return nil
	}
	out := new(EntityWorkflowStatus)
	in.DeepCopyInto(out)
	return out
}
